// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBa8Jw5F2MdwtfTpOrRDrzEOqreuPAyOg',
    appId: '1:1097394554952:web:84832b380fe85a7d5b307d',
    messagingSenderId: '1097394554952',
    projectId: 'mobile-modul-6-eb468',
    authDomain: 'mobile-modul-6-eb468.firebaseapp.com',
    storageBucket: 'mobile-modul-6-eb468.firebasestorage.app',
    measurementId: 'G-ZTS4VESECN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDepMj25Pd9XyLfEudPu35klnc25Nj_CMo',
    appId: '1:1097394554952:android:62b4e40dbd06e02b5b307d',
    messagingSenderId: '1097394554952',
    projectId: 'mobile-modul-6-eb468',
    storageBucket: 'mobile-modul-6-eb468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0uIj-yXVa4darptsPeW-0d5PjPkZ-LG8',
    appId: '1:1097394554952:ios:2ada908b00daae225b307d',
    messagingSenderId: '1097394554952',
    projectId: 'mobile-modul-6-eb468',
    storageBucket: 'mobile-modul-6-eb468.firebasestorage.app',
    iosBundleId: 'com.example.modul3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0uIj-yXVa4darptsPeW-0d5PjPkZ-LG8',
    appId: '1:1097394554952:ios:2ada908b00daae225b307d',
    messagingSenderId: '1097394554952',
    projectId: 'mobile-modul-6-eb468',
    storageBucket: 'mobile-modul-6-eb468.firebasestorage.app',
    iosBundleId: 'com.example.modul3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBa8Jw5F2MdwtfTpOrRDrzEOqreuPAyOg',
    appId: '1:1097394554952:web:84832b380fe85a7d5b307d',
    messagingSenderId: '1097394554952',
    projectId: 'mobile-modul-6-eb468',
    authDomain: 'mobile-modul-6-eb468.firebaseapp.com',
    storageBucket: 'mobile-modul-6-eb468.firebasestorage.app',
    measurementId: 'G-ZTS4VESECN',
  );

}